version: '3.8'

services:
  backend:
    build:
      context: ./music-system
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JWT_SECRET=z/GWLDiagvqgIfkuFj2TOUvSMurT37wilpRGRQfy3ZmJip64ru2fKZkzcgMgibC+qtPrRC0HeoJAU1Umy/8sbw==
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/test
      - SPRING_DATASOURCE_USERNAME=vladimirdemurchian
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: vladimirdemurchian
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vladimirdemurchian"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./music-system-client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
